services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - .env.docker
    depends_on:
      redis_cache:
        condition: service_started
    links:
      - redis_cache

  redis_cache:
    image: redis:8.0.0-alpine
    env_file:
      - .env.docker
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  test:
    profiles: ["test"]
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: gradle test
    env_file:
      - .env.docker
    depends_on:
      - redis_cache
    links:
      - redis_cache



volumes:
  redis_data: